FROM ubuntu:latest

LABEL version="1.0.0"
LABEL maintainer="ogunyemitaiwojohn@gmail.com"

RUN apt-get update
RUN apt-get upgrade -y

RUN app-get install nginx -y

EXPOSE 80

CMD [ "nginx", "-g", "daemon off";]